import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getSession } from '@/lib/auth/session'
import { auditService } from '@/lib/services/audit'
import { handleAPIError, AppError } from '@/lib/errors'
import { z } from 'zod'
import { Prisma } from '@prisma/client'

// Validation schema for creating a client
const createClientSchema = z.object({
  phone_e164: z.string().regex(/^\+[0-9]{1,3}[0-9]{6,14}$/, 'Invalid phone number format (E.164 required)'),
  first_name: z.string().min(1, 'First name is required').max(100),
  last_name: z.string().min(1, 'Last name is required').max(100),
  gender: z.enum(['male', 'female', 'other']).optional(),
  age: z.number().int().min(1).max(120).optional(),
  goal: z.string().max(255).optional(),
  source: z.enum(['landing', 'social', 'sales', 'referral', 'campaign', 'post_payment']),
})

/**
 * GET /api/clients
 * Fetch all clients for the current tenant with search, filters, sorting, and pagination
 */
export async function GET(request: NextRequest) {
  try {
    const session = await getSession(request)
    const { searchParams } = new URL(request.url)

    // Parse query parameters
    const page = parseInt(searchParams.get('page') || '1')
    const pageSize = parseInt(searchParams.get('pageSize') || '50')
    const search = searchParams.get('search') || ''
    const status = searchParams.get('status') || ''
    const goal = searchParams.get('goal') || ''
    const sortBy = searchParams.get('sortBy') || 'created_at'
    const sortOrder = (searchParams.get('sortOrder') || 'desc') as 'asc' | 'desc'

    // Build where clause
    const where: Prisma.customersWhereInput = {
      tenant_id: BigInt(session.user.tenant_id),
      // Exclude soft-deleted clients
      ...(status && { status: status as any }),
      ...(goal && { goal: { contains: goal, mode: 'insensitive' } }),
      ...(search && {
        OR: [
          { first_name: { contains: search, mode: 'insensitive' } },
          { last_name: { contains: search, mode: 'insensitive' } },
          { phone_e164: { contains: search } },
        ],
      }),
    }

    // Fetch data with pagination
    const [rows, total] = await Promise.all([
      prisma.customers.findMany({
        where,
        orderBy: { [sortBy]: sortOrder },
        skip: (page - 1) * pageSize,
        take: pageSize,
        select: {
          id: true,
          phone_e164: true,
          first_name: true,
          last_name: true,
          gender: true,
          age: true,
          status: true,
          goal: true,
          source: true,
          created_at: true,
          updated_at: true,
        },
      }),
      prisma.customers.count({ where }),
    ])

    // Convert BigInt to string for JSON serialization
    const serializedRows = rows.map(row => ({
      ...row,
      id: row.id.toString(),
    }))

    return NextResponse.json({
      rows: serializedRows,
      total,
      page,
      pageSize,
    })
  } catch (error) {
    return handleAPIError(error)
  }
}

/**
 * POST /api/clients
 * Create a new client
 */
export async function POST(request: NextRequest) {
  try {
    const session = await getSession(request)
    const body = await request.json()

    // Validate input
    const data = createClientSchema.parse(body)

    // Check for duplicate phone number within tenant
    const existing = await prisma.customers.findFirst({
      where: {
        tenant_id: BigInt(session.user.tenant_id),
        phone_e164: data.phone_e164,
      },
    })

    if (existing) {
      throw new AppError(
        'A client with this phone number already exists',
        400,
        'DUPLICATE_PHONE'
      )
    }

    // Create client (ClientCode will be auto-generated by database trigger)
    const client = await prisma.customers.create({
      data: {
        tenant_id: BigInt(session.user.tenant_id),
        phone_e164: data.phone_e164,
        first_name: data.first_name,
        last_name: data.last_name,
        gender: data.gender,
        age: data.age,
        goal: data.goal,
        source: data.source,
        status: 'lead',
        region: 'MENA',
        language: 'en',
      },
    })

    // Log to audit
    await auditService.logCreate(
      session.user.tenant_id,
      session.user.id,
      'customer',
      Number(client.id),
      {
        phone_e164: data.phone_e164,
        first_name: data.first_name,
        last_name: data.last_name,
        status: 'lead',
      }
    )

    // Convert BigInt to string
    const serializedClient = {
      ...client,
      id: client.id.toString(),
      tenant_id: client.tenant_id.toString(),
    }

    return NextResponse.json(serializedClient, { status: 201 })
  } catch (error) {
    return handleAPIError(error)
  }
}
