// lib/api/endpoints.ts
export const endpoints = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    logout: '/auth/logout',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    currentUser: '/auth/user',
    requestOtp: '/auth/request-otp',
    verifyOtp: '/auth/verify-otp',
    lockout: '/auth/lockout',
  },
  admin: {
    analytics: {
      dashboard: '/admin/analytics/dashboard',
      clients: '/admin/analytics/clients',
      trainers: '/admin/analytics/trainers',
    },
    users: '/admin/users',
    settings: '/admin/settings',
    billing: {
      subscriptions: '/admin/billing/subscriptions',
      invoices: '/admin/billing/invoices',
      payments: '/admin/billing/payments',
      plans: '/admin/billing/plans',
    },
    support: {
      tickets: '/admin/support/tickets',
      categories: '/admin/support/categories',
    },
  },
  client: '/clients',
  clientActivities: (id: string) => `/clients/${id}/activities`,
  clientProgress: (id: string) => `/clients/${id}/progress`,
  clientPrograms: (id: string) => `/clients/${id}/programs`,
  appointment: '/appointments',
  checkIn: '/check-ins',
  customerMetric: '/customer-metrics',
  message: '/messages',
  metricDefinition: '/metric-definitions',
  notification: '/notifications',
  notificationRead: (id: string) => `/notifications/${id}/read`,
  nutrition: '/nutrition-plans',
  nutritionLog: '/nutrition-logs',
  progress: '/progress',
  referral: '/referrals',
  reports: '/reports',
  trainer: '/trainers',
  workout: '/workouts',
  exercise: '/exercises',
  support: '/support'
};